services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: dev
    image: laravel-octane-php
    container_name: 'laravel-octane-container'
    entrypoint: [php]
    command: ["/application/artisan", "serve", "--port=80", "--host=0.0.0.0"]
    volumes:
      - .:/application
    ports:
      - 8000:80
